# Change these first
owner: launchforge # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Web - Homepage
    url: https://launchforge.co
    showAverageResponseTime: false
  - name: Web - App
    url: https://app.launchforge.co
    showAverageResponseTime: false
  - name: Services - API
    url: https://services.launchforge.co/api/v1/health
    showAverageResponseTime: false
  - name: Services - Authentication
    url: https://services.launchforge.co/auth/health/alive
    showAverageResponseTime: false
  - name: Services - Content Delivery Network
    url: https://launchforge-prod.s3.us-west-002.backblazeb2.com/
    expectedStatusCodes:
      - 200
      - 403
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.launchforge.co
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Launchforge
  introTitle: "**Launchforge** Service Status"
  introMessage: Reporting the status of Launchforge websites and services, hosted on Github. If anything goes down, you'll know about it here.
  navbar:
    - title: Status
      href: /
    - title: App
      href: https://app.launchforge.co

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - jamieshepherd